# @base_url = http://52.91.75.107:3000
@base_url = http://localhost:3001
###
@client_id = 7536a7f2-cf05-473f-923c-b89bb784f9a9
@product_id = 87e6283a-1d73-44d9-8ff9-d33831c5eb98
@domicile_id = 2d545c54-8954-429c-ad54-9f9fd09b8d67
@sales_id = c1c57212-6423-4115-881e-e6628f4f35f3


### post sales ####
POST {{base_url}}/sales
Content-Type: application/json

{
    "clientId": "{{client_id}}",
    "billingAddressId": "{{domicile_id}}",
    "shippingAddressId": "{{domicile_id}}",
    "total": 1000,
    "productId": "{{product_id}}",
    "quantity": 1,
    "amount": 1000
}

### get sales ####
GET  {{base_url}}/sales/{{sales_id}}


### get pdf ####
GET  {{base_url}}/sales/{{sales_id}}/pdf

